spring:
  application:
    name: app1
  jpa:
    open-in-view: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        jdbc:
        #          batch_size: 100
        query:
          in_clause_parameter_padding: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: false
  datasource:
    name: cloudexample1
    url: jdbc:postgresql://127.0.0.1:5432/${spring.datasource.name}
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

  flyway:
    baseline-on-migrate: true
    out-of-order: true


  security:
    oauth2:
      resource:
        token-info-uri: http://localhost:9000/oauth/check_token
        user-info-uri: http://localhost:9000/user
      client:
        client-id: web-client
        client-secret: 123456


server:
  port: 8081
