hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eureka:
    enabled: false


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: app1
          uri: http://localhost:8081
          predicates:
            - Path=/app1/**
        - id: app2
          uri: lb://app2
          predicates:
            - Path=/app2/**
        - id: resource
          uri: http://localhost:8090
          predicates:
            - Path=/resource
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
    discovery:
      locator: true
      lowerCaseServiceId: true
      enabled: true
    config:
      uri: http://localhost:8081
  security:
  oauth2:
    client:
      registration:
        gateway:
          provider: spring
          client-id: gateway
          client-secret: secret
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope: openid,resource.read
      provider:
        spring:
          issuer-uri: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true

server:
  port: 9090


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
