

###
GET http://localhost:8989/app2/getInfo
###
POST http://192.168.3.199/api/template

###
GET http://localhost:8989/resource
Authorization: Bearer eyJraWQiOiIwMGNhMTc2OS00ODdkLTQ4NDItYWQ2MS03M2YyMGNhYTdkZjIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnYXRld2F5IiwiYXVkIjoiZ2F0ZXdheSIsIm5iZiI6MTY4NjY2NjU3NSwic2NvcGUiOlsib3BlbmlkIiwicmVzb3VyY2UucmVhZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY4NjY2Njg3NSwiaWF0IjoxNjg2NjY2NTc1fQ.ijpdhTo-Yb-Zn710B7hEn0bh2AjFB36Ih5h5BOa61mwpNHGw-anWdqYMZuccxeJ75M7422j3QCJr83tXUdmrHZQoWzsnoQ7fMnewVD5X2idJya5ZLvZeXfLQ0EEnEGmlF23hdWogG3aVknDjPy_lXZsfS0YdbF2-UbEL4fA2ww_aV1vLFz0iyFiqnMUbXvNZZIkFGZ7yhadZguua95mnFRLP-5N0AhNgcUwDJwHE3BpL5VPwYvv8ggJcRrEw1iRXUsBitM3GRIRNPt10xiwUuyr1dkJVsnHrmj3o58EDOkYaDA4-C6hbqdGWn41rLKwMOV2j5TuncA1kfC7kLaTMyw


###
GET http://localhost:8989/actuator/gateway/routes



###
GET http://localhost:8082/getInfo

###

# curl --location --request GET 'http://localhost:7777/oauth2/authorize?response_type=code&client_id=test-client&redirect_uri=http://localhost:5000/code
GET http://localhost:9000/oauth2/authorize?response_type=code&client_id=gateway&redirect_uri=http://localhost:5000/code

###
GET http://localhost:9000/oauth2/authorize?response_type=code&client_id=gateway&redirect_uri=http://127.0.0.1:8080/authorized&scope=openid read



###
# curl -X POST 'http://localhost:9090/oauth2/token?grant_type=client_credentials'
#  --header 'Authorization: Basic b2F1dGgtY2xpZW50Om9hdXRoLXNlY3JldA=='
POST http://localhost:9000/oauth2/token?grant_type=client_credentials
Authorization: Basic Z2F0ZXdheTpzZWNyZXQ=

###
POST http://localhost:8989//oauth2/token?grant_type=client_credentials
Authorization: Basic Z2F0ZXdheTpzZWNyZXQ=


###

# curl --location --request POST 'http://localhost:7777/oauth2/token?grant_type=client_credentials'
#--header 'Authorization: Basic dGVzdC1jbGllbnQ6dGVzdC1jbGllbnQ='
POST http://localhost:9000/oauth2/token?grant_type=authorization_code
Authorization: Basic Z2F0ZXdheTpzZWNyZXQ=

###
GET http://localhost:9000/.well-known/oauth-authorization-server

###
GET http://localhost:8081/articles
Authorization: Basic eyJraWQiOiJhNzdlYmI3Yi01NTYwLTQ3ZGMtYjMzMi0xNmQ4YzYxMGZlZGQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnYXRld2F5IiwiYXVkIjoiZ2F0ZXdheSIsIm5iZiI6MTY4Njc0ODk0OSwic2NvcGUiOlsib3BlbmlkIiwicmVzb3VyY2UucmVhZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY4Njc0OTI0OSwiaWF0IjoxNjg2NzQ4OTQ5fQ.Vm7pyxek0l3cbU3X_iV_OJqOR1cG7n-wVNCH1C6uRlFvHD6LUWxAfT6oFkeLGnVSXK84YLuQOuXJMyHl3hACDjXap1FLmoKOQd8CQP8YEHqxiRGjbDIJKpas2eF3oLVYsaoKMWBx_0pmhxdHrmPhX2vlDnfGk6JNmuX23YWnFYGYgM__-jzn5kIWe-h9tClSjW-iJFyvW662m_ZnyCbBZO_k88aCVN5Sf8A_3RGcai-jXf_sVVAp_j0PRXLYNzj_yPQ4MUMnjncwIhuI8AO-UlRFhq0VsSK5k1ygeqp36Qj6sbWBuzct1i3Y3MB3sI1YY9sN_m7yavqM-GlUwJednA