

###
GET http://localhost:8989/app2/getInfo
Authorization:  Bearer eyJraWQiOiI3NGM4ZjYwMy03N2ZkLTQ4ZmUtYTIyZi03NWRkNzRiZjVmMGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnYXRld2F5IiwiYXVkIjoiZ2F0ZXdheSIsIm5iZiI6MTY4NzY5OTI0NCwic2NvcGUiOlsib3BlbmlkIiwicmVzb3VyY2UucmVhZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY4NzY5OTU0NCwiaWF0IjoxNjg3Njk5MjQ0fQ.Wzp38vO0ZojdM2ncUCOGD4EuGnJHqP1LOt4e-kd7JwNU0uqky2bNrIBhTT7u3mgJiOHoQGXgTOLVw0bCeQpt_16D3VrFsHVBAc6RCUkY_guP7h_55-6lnNt95EzMmvTjKRX3EPW54zHF7aQgq0enSCO9dSuxSkgrBc35qTEADjj_T33tIEV7B-MJ_03oRNskG2P04hUNr0rIZo8AUzpWuSNJmj29b8_xTkT5PAEYCQA1zEJ8KW7YfLgGLLt0kdKdgggIniaBlfGsyyCZUg3fHmKjFAl1IcWUmKjahB0dsd1OK7LiFrv9waQ0SLTiG3svyNu6evKYT249pHca9u594w

###
GET http://localhost:8989/app1/addInfo
Authorization:  Bearer eyJraWQiOiI3NGM4ZjYwMy03N2ZkLTQ4ZmUtYTIyZi03NWRkNzRiZjVmMGYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnYXRld2F5IiwiYXVkIjoiZ2F0ZXdheSIsIm5iZiI6MTY4NzY5OTI0NCwic2NvcGUiOlsib3BlbmlkIiwicmVzb3VyY2UucmVhZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY4NzY5OTU0NCwiaWF0IjoxNjg3Njk5MjQ0fQ.Wzp38vO0ZojdM2ncUCOGD4EuGnJHqP1LOt4e-kd7JwNU0uqky2bNrIBhTT7u3mgJiOHoQGXgTOLVw0bCeQpt_16D3VrFsHVBAc6RCUkY_guP7h_55-6lnNt95EzMmvTjKRX3EPW54zHF7aQgq0enSCO9dSuxSkgrBc35qTEADjj_T33tIEV7B-MJ_03oRNskG2P04hUNr0rIZo8AUzpWuSNJmj29b8_xTkT5PAEYCQA1zEJ8KW7YfLgGLLt0kdKdgggIniaBlfGsyyCZUg3fHmKjFAl1IcWUmKjahB0dsd1OK7LiFrv9waQ0SLTiG3svyNu6evKYT249pHca9u594w


###
POST http://192.168.3.199/api/template

###
GET http://localhost:8989/resource
Authorization: Bearer eyJraWQiOiIwMGNhMTc2OS00ODdkLTQ4NDItYWQ2MS03M2YyMGNhYTdkZjIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnYXRld2F5IiwiYXVkIjoiZ2F0ZXdheSIsIm5iZiI6MTY4NjY2NjU3NSwic2NvcGUiOlsib3BlbmlkIiwicmVzb3VyY2UucmVhZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY4NjY2Njg3NSwiaWF0IjoxNjg2NjY2NTc1fQ.ijpdhTo-Yb-Zn710B7hEn0bh2AjFB36Ih5h5BOa61mwpNHGw-anWdqYMZuccxeJ75M7422j3QCJr83tXUdmrHZQoWzsnoQ7fMnewVD5X2idJya5ZLvZeXfLQ0EEnEGmlF23hdWogG3aVknDjPy_lXZsfS0YdbF2-UbEL4fA2ww_aV1vLFz0iyFiqnMUbXvNZZIkFGZ7yhadZguua95mnFRLP-5N0AhNgcUwDJwHE3BpL5VPwYvv8ggJcRrEw1iRXUsBitM3GRIRNPt10xiwUuyr1dkJVsnHrmj3o58EDOkYaDA4-C6hbqdGWn41rLKwMOV2j5TuncA1kfC7kLaTMyw


###
GET http://localhost:8989/actuator/gateway/routes
Authorization:  Bearer eyJraWQiOiIxNThkYjliYS04NGJmLTQ2ZTAtOTVjOC0wMjQ5NzgzOGRjOTYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnYXRld2F5IiwiYXVkIjoiZ2F0ZXdheSIsIm5iZiI6MTY4NzY5Nzg5OSwic2NvcGUiOlsib3BlbmlkIiwicmVzb3VyY2UucmVhZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY4NzY5ODE5OSwiaWF0IjoxNjg3Njk3ODk5fQ.VbJKDUeIz-BO92bLUfEGOc7OyJDMaUCsfTJcTdedFfaS-8VSGBxTDRjTDGDpEyz96XCjFtfac0d-ua2nyny1op8s7mpTJ9peMiRltHWULt_3Jv4LHIwI2i3d72uLcvXOr5flxIHitcxILksQssEF_ARXgBqyYE6Bxb7VzrS53nrMe96iOLbHNTjHGQRuEldxywN9SMnVA7PErcWt7zSOmnIpGD4n0ECfdCXfCrjx5tLJ1OImPc0Vj52V9gyeBjmLaOJ7m2Q19VGXYCBXEcA3RyKtt0jynuaY9lk-xnCyxLEmTQQrFFhQaKVTzROaAAv0JqN047Bn3girWrhobh9f9Q


###
GET http://localhost:8082/getInfo
Authorization:  Bearer eyJraWQiOiIxNThkYjliYS04NGJmLTQ2ZTAtOTVjOC0wMjQ5NzgzOGRjOTYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnYXRld2F5IiwiYXVkIjoiZ2F0ZXdheSIsIm5iZiI6MTY4NzY5Nzg5OSwic2NvcGUiOlsib3BlbmlkIiwicmVzb3VyY2UucmVhZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY4NzY5ODE5OSwiaWF0IjoxNjg3Njk3ODk5fQ.VbJKDUeIz-BO92bLUfEGOc7OyJDMaUCsfTJcTdedFfaS-8VSGBxTDRjTDGDpEyz96XCjFtfac0d-ua2nyny1op8s7mpTJ9peMiRltHWULt_3Jv4LHIwI2i3d72uLcvXOr5flxIHitcxILksQssEF_ARXgBqyYE6Bxb7VzrS53nrMe96iOLbHNTjHGQRuEldxywN9SMnVA7PErcWt7zSOmnIpGD4n0ECfdCXfCrjx5tLJ1OImPc0Vj52V9gyeBjmLaOJ7m2Q19VGXYCBXEcA3RyKtt0jynuaY9lk-xnCyxLEmTQQrFFhQaKVTzROaAAv0JqN047Bn3girWrhobh9f9Q

###

# curl --location --request GET 'http://localhost:7777/oauth2/authorize?response_type=code&client_id=test-client&redirect_uri=http://localhost:5000/code
GET http://localhost:9000/oauth2/authorize?response_type=code&client_id=gateway&redirect_uri=http://localhost:5000/code

###
GET http://localhost:9000/oauth2/authorize?response_type=code&client_id=gateway&redirect_uri=http://127.0.0.1:8080/authorized&scope=openid read



###
# curl -X POST 'http://localhost:9090/oauth2/token?grant_type=client_credentials'
#  --header 'Authorization: Basic b2F1dGgtY2xpZW50Om9hdXRoLXNlY3JldA=='
POST http://localhost:9000/oauth2/token?grant_type=client_credentials
Authorization: Basic Z2F0ZXdheTpzZWNyZXQ=

###
POST http://localhost:8989//oauth2/token?grant_type=client_credentials
Authorization: Basic Z2F0ZXdheTpzZWNyZXQ=


###

# curl --location --request POST 'http://localhost:7777/oauth2/token?grant_type=client_credentials'
#--header 'Authorization: Basic dGVzdC1jbGllbnQ6dGVzdC1jbGllbnQ='
POST http://localhost:9000/oauth2/token?grant_type=authorization_code
Authorization: Basic Z2F0ZXdheTpzZWNyZXQ=

###
GET http://localhost:9000/.well-known/oauth-authorization-server

###
GET http://localhost:8081/articles
Authorization:  Bearer eyJraWQiOiIxNThkYjliYS04NGJmLTQ2ZTAtOTVjOC0wMjQ5NzgzOGRjOTYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnYXRld2F5IiwiYXVkIjoiZ2F0ZXdheSIsIm5iZiI6MTY4NzY5Nzg5OSwic2NvcGUiOlsib3BlbmlkIiwicmVzb3VyY2UucmVhZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY4NzY5ODE5OSwiaWF0IjoxNjg3Njk3ODk5fQ.VbJKDUeIz-BO92bLUfEGOc7OyJDMaUCsfTJcTdedFfaS-8VSGBxTDRjTDGDpEyz96XCjFtfac0d-ua2nyny1op8s7mpTJ9peMiRltHWULt_3Jv4LHIwI2i3d72uLcvXOr5flxIHitcxILksQssEF_ARXgBqyYE6Bxb7VzrS53nrMe96iOLbHNTjHGQRuEldxywN9SMnVA7PErcWt7zSOmnIpGD4n0ECfdCXfCrjx5tLJ1OImPc0Vj52V9gyeBjmLaOJ7m2Q19VGXYCBXEcA3RyKtt0jynuaY9lk-xnCyxLEmTQQrFFhQaKVTzROaAAv0JqN047Bn3girWrhobh9f9Q
