spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8001
      fail-fast: true
      password: admin
      username: user
      enabled: true
  config:
    import: optional:configserver:http://localhost:8001