spring:
  application:
    name: Banner App
  jpa:
    open-in-view: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        jdbc:
        #          batch_size: 100
        query:
          in_clause_parameter_padding: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: false
  datasource:
    name: banner
    url: jdbc:postgresql://127.0.0.1:5432/${spring.datasource.name}
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    out-of-order: true

logging:
  level:
    ROOT: info
    org.springframework.web.reactive.function.client.ExchangeFunctions: trace
    io.minery: trace
    org.hibernate.SQL: INFO
    io.swagger.models.parameters.AbstractSerializableParameter: error
    springfox.documentation.schema.property.CachingModelPropertiesProvider: error
    #    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    #    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org.springframework.r2dbc: INFO
    #    reactor.netty: debug
    reactor.netty.http.client: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
